## Copyright (C) 2011(-2023) Reinhard <octave-user@a1.net>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; If not, see <http://www.gnu.org/licenses/>.

## -*- texinfo -*-
## mboct-fem-pkg is a small and lightweight finite element toolkit for GNU-Octave.
## It can be used as a pre- and post-processor for MBDyn's modal elements (www.mbdyn.org).
## Simple meshes can be generated by means of the built in hexahedral mesh generator.
## More complex tetrahedral and hexahedral meshes can be imported from Gmsh, EOSSP and APDL.
## Post-processing is possible either within GNU-Octave or with Gmsh as post-processor.

