name: cleanup caches by a branch
on:
  push:
    branches: [ "pastix" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          gh cache list
          gh cache delete --all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
