name: cleanup caches by a branch
on:
  push:
    branches: [ "pastix" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache list -R $REPO
          gh actions-cache delete -R $REPO --all --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
