name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '18 19 * * *'
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Install GNU/Octave
        run: |
           sudo apt-get update
           sudo apt-get dist-upgrade
           sudo apt-get install octave liboctave-dev \
           libsuitesparse-dev libarpack2-dev libmumps-seq-dev \
           libmetis-dev octave-nurbs libnlopt-dev \
           libmkl-full-dev
      # Runs a single command using the runners shell
      - name: Install Gmsh
        run: |
           wget http://www.gmsh.info/bin/Linux/gmsh-4.8.4-Linux64.tgz
           tar -zxvf gmsh-4.8.4-Linux64.tgz
           sudo install gmsh-4.8.4-Linux64/bin/gmsh /usr/local/bin
           gmsh --version
      # Runs a set of commands using the runners shell
      - name: Install MBDyn
        run: |
          wget https://public.gitlab.polimi.it/DAER/mbdyn/-/archive/develop/mbdyn-develop.tar.bz2 && \
          tar -jxvf mbdyn-develop.tar.bz2 && \
          pushd mbdyn-develop && \
          ./bootstrap.sh && \
          ./configure --with-static-modules \
          --enable-octave --enable-sparse_autodiff --enable-autodiff \
          --disable-Werror CXXFLAGS="-Ofast -Wall -march=native" CPPFLAGS=-I/usr/include/suitesparse \
          --with-arpack --with-umfpack --without-metis && \
          make -j4 && sudo make install && popd
      - name: Install mboct-octave-pkg
        run: |
           git clone -b master https://github.com/octave-user/mboct-octave-pkg.git && \
           pushd mboct-octave-pkg && \
           sudo make CXXFLAGS="-Ofast -Wall -march=native" install_global && popd
      - name: Install mboct-numerical-pkg
        run: |
           git clone -b master https://github.com/octave-user/mboct-numerical-pkg.git && \
           pushd mboct-numerical-pkg && \
           sudo make CXXFLAGS="-Ofast -Wall -march=native" install_global && popd
      - name: Install mboct-mbdyn-pkg
        run: |
           git clone -b master https://github.com/octave-user/mboct-mbdyn-pkg.git && \
           pushd mboct-mbdyn-pkg && \
           sudo make CXXFLAGS="-Ofast -Wall -march=native" install_global && popd
      - name: Install the package
        run: sudo make -C $GITHUB_WORKSPACE CXXFLAGS="-Ofast -Wall -march=native" install_global

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
