name: Docker-hub

on:
  schedule:
    - cron: '0 5 * * sun'
  push:
    branches: ["master", "docker-publish"]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          provenance: mode=max
          sbom: true
          build-args: MBOCT_FEM_PKG_BRANCH=${{ github.head_ref != '' && github.head_ref || github.ref_name }}
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/mboct-fem-pkg:latest
