# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install GNU/Octave
        run: |
           sudo apt-get install octave liboctave-dev \
           libsuitesparse-dev libarpack2-dev libmumps-seq-dev \
           libmetis-dev octave-nurbs gmsh
      # Runs a set of commands using the runners shell
      - name: Install MBDyn
        run: |
          git clone -b develop https://public.gitlab.polimi.it/DAER/mbdyn.git && \
          pushd mbdyn && \
          ./bootstrap.sh && \
          ./configure --with-static-modules \
          --enable-octave --enable-sparse_autodiff --enable-autodiff \
          --disable-Werror CPPFLAGS=-I/usr/include/suitesparse \
          --with-arpack --with-umfpack --without-metis && \
          make && sudo make install && popd
      - name: Install mboct-octave-pkg
        run: |
           git clone -b master https://github.com/octave-user/mboct-octave-pkg.git && \
           pushd mboct-octave-pkg && \
           make install_local && popd
           
      - name: Install mboct-numerical-pkg
        run: |
           git clone -b master https://github.com/octave-user/mboct-numerical-pkg.git && \
           pushd mboct-numerical-pkg && \
           make install_local && popd
           
      - name: Install mboct-mbdyn-pkg
        run: |
           git clone -b master https://github.com/octave-user/mboct-mbdyn-pkg.git && \
           pushd mboct-mbdyn-pkg && \
           make install_local && popd           
           
      - name: Create distribution
        run: make -C $GITHUB_WORKSPACE dist
        
      - name: Install the package
        run: make -C $GITHUB_WORKSPACE install_local
        
      - name: Run all tests
        run: make -C $GITHUB_WORKSPACE check_installed
